Update databricks diagnostic setting policy
Azure/Enterprise-Scale pull request #1126
Opened 2022-11-17 20:56 UTC by chrholt

## Overview/Summary

Added missing log categories for "**Deploy Diagnostic Settings for Databricks to Log Analytics workspace**"" policy definition.

## This PR fixes/adds/changes/removes

1. Adds log categories for policy definition
  - Databricks SQL Analytics
  - Databricks Genie
  - Databricks Global init Scripts
  - Databricks IAM Role
  - Databricks MLFlow Experiment
  - Databricks Feature Store
  - Databricks Remote History Service
  - Databricks MLFlow Acled Artifact
  - Databricks DatabricksSQL
  - Databricks Delta Pipelines
  - Databricks Model Registry
  - Databricks Repos
  - Databricks Unity Catalog
  - Databricks Git Credentials
  - Databricks Web Terminal 

### Breaking Changes

1. *Replace me*
3. *Replace me*

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fchrholt%2FEnterprise-Scale%2Fupdate-databricks-diagnostic-setting%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fchrholt%2FEnterprise-Scale%2Fupdate-databricks-diagnostic-setting%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fchrholt%2FEnterprise-Scale%2Fupdate-databricks-diagnostic-setting%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2022-11-17 20:59 UTC, chrholt commented
#1123

2022-11-17 21:14 UTC, chrholt commented
@microsoft-github-policy-service agree

2022-11-17 21:48 UTC, jtracey93 requested changes
Thanks @chrholt for the quick turnaround here.

I have left one comment and could I also ask you increment the version in `src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Databricks.json` (in the metadata) to `1.2.0` as per https://github.com/Azure/azure-policy/blob/master/built-in-policies/README.md#versioning

2022-11-17 21:48 UTC, jtracey93 commented on docs/wiki/Whats-new.md
> +  - [Other](#other)
Could you revert all of these changes back. Suspect it's an extension that's done this 👎

We just want the month headings in the TOC

2022-11-18 09:13 UTC, jtracey93 commented
@chrholt is this good to review again?

2022-11-18 09:16 UTC, chrholt commented
> @chrholt is this good to review again?

Yes, I believe I figured it out now. Got a lot of unintensional changes in markdown files caused by extensions..

2022-11-21 11:19 UTC, jtracey93 approved these changes
LGTM

2022-11-21 11:19 UTC, merged