Add policy definitions to help secure data workloads
Azure/Enterprise-Scale pull request #1144
Opened 2022-11-30 14:50 UTC by krowlandson

## Overview/Summary

This PR adds a number of policy definitions previously authored by @marvinbuss, and supersedes the following PRs:

- #756
- #758
- #759
- #760
- #761
- #762
- #763
- #764
- #765
 
These policies need to be reviewed before this PR is merged. These are our initial observations against the current available built-in policies:

| Custom Policy Definition ID | Observations |
| --- | --- |
| `Append-Synapse-Purview` | Has no built-in matches. |
| `Deny-Cosmos-Cors` | Has no built-in matches. |
| `Deny-Cosmos-KeyBasedMetadataWriteAccess` | Similar to `4750c32b-89c0-46af-bfcb-2e4541a818d5` but the built-in policy uses an `append` effect instead of - `Deny`. |
| `Deny-DataExplorer-Sku` | Has no built-in matches. |
| `Deny-DataExplorer-TrustedExternalTenants` | Has no built-in matches. |
| `Deny-DataFactory-ApiVersion` | Has no built-in matches. |
| `Deny-DataFactory-IdentityType` | Has no built-in matches. (similar to `f78ccdb4-7bf4-4106-8647-270491d2978a` but the built-in is for Azure Data Factory linked services) |
| `Deny-DataFactory-IntegrationRuntimeManagedVirtualNetwork` | Has no built-in matches. (similar to `0088bc63-6dee-4a9c-9d29-91cfdc848952` but not a suitable alternative) |
| `Deny-DataFactory-ManagedPrivateEndpoints` | Has no built-in matches. (extends the controls relating to `8b0323be-cc25-4b61-935d-002c3798c6ea`) |
| `Deny-DataFactory-PublicNetworkAccess` | Matches the built-in policy `1cf164be-6819-4a50-b8fa-4bcaa4f98fb6`. Consider removing. |
| `Deny-EventHub-IpFilterRules` | Has no built-in matches. |
| `Deny-EventHub-MaximumThroughputUnits` | Has no built-in matches. |
| `Deny-EventHub-NetworkRuleSet` | Has no built-in matches. |
| `Deny-EventHub-Sku` | Has no built-in matches. |
| `Deny-EventHub-VNetRules` | Has no built-in matches. |
| `Deny-HdInsight-MinimalTlsVersion` | Has no built-in matches. |
| `Deny-HdInsight-NetworkProperties` | Similar to `c8cc2f85-e019-4065-9fa3-5e6a2b2dde56`. Needs evaluation. |
| `Deny-HdInsight-Sku` | Has no built-in matches. |
| `Deny-IotHub-MinimalTlsVersion` | Has no built-in matches. |
| `Deny-IotHub-Sku` | Has no built-in matches. |
| `Deny-Search-PublicNetworkAccess` | Similar to `9cee519f-d9c1-4fd9-9f79-24ec3449ed30` but built-in uses `modify` effect instead of `deny` |
| `Deny-Search-Sku` | Has no built-in matches. |
| `Deny-StreamAnalytics-ClusterId` | Has no built-in matches. |
| `Deny-StreamAnalytics-StreamingUnits` | Has no built-in matches. |
| `Deny-Synapse-Firewall` | Similar to `56fd377d-098c-4f02-8406-81eb055902b8` but built-in uses `audit` effect instead of `deny` |
| `Deny-Synapse-LinkedAccessCheckOnTargetResource` | Has no built-in matches. |
| `Deny-Synapse-Spark-AutoPause` | Has no built-in matches. |
| `Deny-Synapse-Spark-AutoScale` | Has no built-in matches. |
| `Deny-Synapse-Spark-ComputeIsolation` | Has no built-in matches. |
| `Deny-Synapse-Spark-DefaultSparkLogFolder` | Has no built-in matches. |
| `Deny-Synapse-Sql-Sku` | Has no built-in matches. |
| `Deploy-DataFactory-ManagedVnet` | Has no built-in matches. |
| `Deploy-Synapse-AuditingSettings` | Similar to `ac7891a4-ac7a-4ba0-9ae9-c923e5a225ee` but potentially not a suitable replacement due to storage account creation logic in built-in. Also `32ba8d30-07c0-4136-ab18-9a11bf4a67b7` might be better option due to using Log Analytics for log storage. |
| `Deploy-Synapse-Sql-AuditingSettings` | Has no built-in matches. |
| `Deploy-Synapse-Sql-MetadataSync` | Has no built-in matches. |
| `Deploy-Synapse-Sql-SecurityAlertPolicies` | Has no built-in matches. (similar for workspaces, but not sqlPools) |
| `Deploy-Synapse-Sql-TransparentDataEncryption` | Similar to `cfaf0007-99c7-4b01-b36b-4048872ac978` but built-in uses `AuditIfNotExists` effect instead of `DeployIfNotExists`. |
| `Deploy-Synapse-Sql-VulnerabilityAssessment` | Has no built-in matches. |
| `Deploy-Synapse-VulnerabilityAssessment` | Similar to `0049a6b3-a662-4f3e-8635-39cf44ace45a` but built-in uses `AuditIfNotExists` effect instead of `DeployIfNotExists`. |

## This PR fixes/adds/changes/removes

1. No linked issues

### Breaking Changes

1. None

## Testing Evidence

Need evidence to validate that these policies all work as expected.

Also need to validate which of these are compatible with `AzureChinaCloud` and `AzureUSGovernment` clouds.

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2022-11-30 14:56 UTC, krowlandson commented
@marvinbuss - these are now ready for you to review and ensure they are still valid. I've provided a quick review in the PR description to identify any possible overlap with built-in policies but do not want to make changes without your input as you were the original contributor for these.

Do you also want to identify at which scopes these should be assigned, otherwise these will not add value to the ALZ reference implementation.

If you feel these are "optional" for customers, perhaps we could add a flag to the implementation options to allow customers to optionally enable these?

2022-12-02 08:37 UTC, marvinbuss requested changes
Great work! 🚀 
Please see comments and suggestions below.

2022-12-02 08:37 UTC, marvinbuss commented on src/resources/Microsoft.Authorization/policyDefinitions/Deny-DataFactory-ManagedPrivateEndpoints.json
> +}
```suggestion
{
  "name": "Deny-DataFactory-ManagedPrivateEndpoints",
  "type": "Microsoft.Authorization/policyDefinitions",
  "apiVersion": "2021-06-01",
  "scope": null,
  "properties": {
    "policyType": "Custom",
    "mode": "All",
    "displayName": "Data Factory should use private endpoints in trusted subscriptions",
    "description": "Denies connecting Data Factory to private endpoints for linked services when not in a specified subscription.",
    "metadata": {
      "version": "1.0.0",
      "category": "Data Factory",
      "source": "https://github.com/Azure/Enterprise-Scale/",
      "alzCloudEnvironments": [
        "AzureCloud",
        "AzureChinaCloud",
        "AzureUSGovernment"
      ]
    },
    "parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "Enable or disable the execution of the policy"
        },
        "allowedValues": [
          "Audit",
          "Disabled",
          "Deny"
        ],
        "defaultValue": "Deny"
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.DataFactory/factories/managedVirtualNetworks/managedPrivateEndpoints"
          },
          {
            "value": "[[split(field('Microsoft.DataFactory/factories/managedVirtualNetworks/managedPrivateEndpoints/privateLinkResourceId'), '/')[2]]",
            "notIn": "[[subscription().subscriptionId]"
          }
        ]
      },
      "then": {
        "effect": "[[parameters('effect')]"
      }
    }
  }
}
```

2022-12-02 08:37 UTC, marvinbuss commented on src/resources/Microsoft.Authorization/policyDefinitions/Deny-DataFactory-ManagedPrivateEndpoints.json
> +}
I don't think we should suggest customers to maintain a list of subscriptions inside their tenant. The proposed solution should cover 99% of the use-cases.

2022-12-02 08:37 UTC, marvinbuss commented on src/resources/Microsoft.Authorization/policyDefinitions/Deny-Synapse-Spark-AutoPause.json
> +}
```suggestion
{
  "name": "Deny-Synapse-Spark-AutoPause",
  "type": "Microsoft.Authorization/policyDefinitions",
  "apiVersion": "2021-06-01",
  "scope": null,
  "properties": {
    "policyType": "Custom",
    "mode": "Indexed",
    "displayName": "Do not allow Auto Pause settings on Synapse Spark Pools",
    "description": "Enforces auto pause settings for Synapse Spark Pools.",
    "metadata": {
      "version": "1.0.0",
      "category": "Synapse"
    },
    "parameters": {
      "effect": {
        "type": "String",
        "metadata": {
          "displayName": "Effect",
          "description": "Enable or disable the execution of the policy"
        },
        "allowedValues": [
          "Audit",
          "Disabled",
          "Deny"
        ],
        "defaultValue": "Deny"
      },
      "maxDelayInMinutes": {
        "type": "Integer",
        "metadata": {
          "displayName": "Maximum Idle Time",
          "description": "Specifies the maximum idle time in minutes until a cluster shuts down"
        },
        "defaultValue": 60
      }
    },
    "policyRule": {
      "if": {
        "allOf": [
          {
            "field": "type",
            "equals": "Microsoft.Synapse/workspaces/bigDataPools"
          },
          {
            "anyOf": [
              {
                "field": "Microsoft.Synapse/workspaces/bigDataPools/autoPause.enabled",
                "notEquals": true
              },
              {
                "field": "Microsoft.Synapse/workspaces/bigDataPools/autoPause.delayInMinutes",
                "greater": "[[parameters('maxDelayInMinutes')]"
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "[[parameters('effect')]"
      }
    }
  }
}
```

2022-12-02 08:37 UTC, marvinbuss commented on src/resources/Microsoft.Authorization/policyDefinitions/Deny-Synapse-Spark-AutoPause.json
> +}
It would be good, if we parametrize the idle time here.

2022-12-02 08:37 UTC, marvinbuss commented on src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Synapse-Sql-MetadataSync.json
> +}
This can be removed. It does not create any value from my perspective.

2023-05-12 11:21 UTC, closed without merging