Add deny create classic resources policy
Azure/Enterprise-Scale pull request #1201
Opened 2023-02-02 16:52 UTC by mbrat2005

## Overview/Summary

Adds a Policy assignment using the built-in deny resource type policy which denies the creation of classic resources at the intermediate root management group. 

## This PR fixes/adds/changes/removes

1. Adds policy assignment definition
2. Adds policy assignment reference to eslzArm.json

### Breaking Changes

## Testing Evidence

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://docs.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmbrat2005%2FEnterprise-Scale%2Fadd-deny-create-classic-resources-policy%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fmbrat2005%2FEnterprise-Scale%2Fadd-deny-create-classic-resources-policy%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fmbrat2005%2FEnterprise-Scale%2Fadd-deny-create-classic-resources-policy%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fmbrat2005%2FEnterprise-Scale%2Fadd-deny-create-classic-resources-policy%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2023-02-03 15:00 UTC, jtracey93 requested changes

2023-02-06 21:33 UTC, mbrat2005 commented on eslzArm/managementGroupTemplates/policyAssignments/DENY-ClassicResourceTypesPolicyAssignment.json
> +                            "Microsoft.ClassicSubscription/operations"
@jtracey93 The built in policy definition for "Not allowed resource types" uses an "in" condition in the rule, which needs to match whole strings.

2023-02-07 09:06 UTC, jtracey93 commented on eslzArm/managementGroupTemplates/policyAssignments/DENY-ClassicResourceTypesPolicyAssignment.json
> +                            "Microsoft.ClassicSubscription/operations"
thanks for confirming and checking

2023-02-07 10:40 UTC, jtracey93 requested changes
Thanks @mbrat2005,

- [ ] Could you also update the wiki doc `/docs/wiki/ALZ-Policies.md`?
- [ ] Also do you think we should expose this on the portal experience? @Springstone thoughts? If so, can you support @mbrat2005 in adding this to his PR?

2023-02-07 10:41 UTC, jtracey93 commented
Deployment succeeded and manually cleaned up - bug #1199 

![image](https://user-images.githubusercontent.com/41163455/217222776-f80b5b15-e3f6-4cce-95db-aea932f45888.png)

2023-02-07 15:18 UTC, mbrat2005 commented
> Thanks @mbrat2005,
> 
> * [ ]  Could you also update the wiki doc `/docs/wiki/ALZ-Policies.md`?
> * [ ]  Also do you think we should expose this on the portal experience? @Springstone thoughts? If so, can you support @mbrat2005 in adding this to his PR?

@jtracey93, I think exposing this in the Portal experience makes sense, especially with the Classic VM retirement moving out to September. I'll add it and test.

2023-02-07 16:03 UTC, jtracey93 commented
> > Thanks @mbrat2005,
> > 
> > * [ ]   Could you also update the wiki doc `/docs/wiki/ALZ-Policies.md`?
> > * [ ]   Also do you think we should expose this on the portal experience? @Springstone thoughts? If so, can you support @mbrat2005 in adding this to his PR?
> 
> @jtracey93, I think exposing this in the Portal experience makes sense, especially with the Classic VM retirement moving out to September.

Yup agreed, maybe expose the radio button on the "Azure Core Setup" blade here:
![image](https://user-images.githubusercontent.com/41163455/217297082-5271b218-8d4c-4b41-97ef-63133ac3198a.png)

Checkout this file and section for inspiration on where to add this https://github.com/Azure/Enterprise-Scale/blob/main/eslzArm/eslz-portal.json#L82

Let me or @Springstone know if you need any assistance

Thanks @mbrat2005

2023-02-07 17:24 UTC, mbrat2005 commented
Added Portal control (both to public and fairfax templates). Tested deployment with default 'yes', 'audit' (deploys, action audit), and 'no' (does not deploy).

![image](https://user-images.githubusercontent.com/25390936/217318743-7d4b4d87-38e3-42c9-a301-3c17a4f57bff.png)

2023-02-07 17:30 UTC, jtracey93 approved these changes
LGTM

2023-02-07 18:37 UTC, jtracey93 commented
Test ran fine, destroy phase is issue (bug #1199)

2023-02-07 18:38 UTC, merged