updating Deny virtual machine with un managed disk policy to Built-in
Azure/Enterprise-Scale pull request #1266
Opened 2023-03-29 13:08 UTC by aarunraaj

## Overview/Summary

Changed Deny virtual machine with Un Managed disk from custom policy to Built-in policy.

## This PR fixes/adds/changes/removes

### Breaking Changes

## Testing Evidence
![image](https://user-images.githubusercontent.com/68339349/228730271-f5115232-94f5-4eea-a17a-9f00b9bdb21c.png)

![image](https://user-images.githubusercontent.com/68339349/228730457-fe37f058-8490-4c8b-8332-89c3f277fda7.png)

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Faarunraaj%2FEnterprise-Scale%2Fpolicy-refresh-unmanageddisk%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Faarunraaj%2FEnterprise-Scale%2Fpolicy-refresh-unmanageddisk%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Faarunraaj%2FEnterprise-Scale%2Fpolicy-refresh-unmanageddisk%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Faarunraaj%2FEnterprise-Scale%2Fpolicy-refresh-unmanageddisk%2FeslzArm%2Feslz-portal.json)

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2023-03-29 15:42 UTC, jtracey93 commented
@springstone, did this get done by you or does this still need doing?

2023-03-29 16:43 UTC, aarunraaj commented
@jtracey93 , its done, but experienced some failure during deployment. So, running few tests.

2023-03-30 10:02 UTC, Springstone commented on docs/wiki/Whats-new.md
> +- Added new assignment to deny deployment of virtual machines and scalesets using unmanaged OS disks.
```suggestion
- Added new assignment to deny deployment of virtual machines and virtual machine scale sets using unmanaged OS disks.
```

2023-03-30 11:16 UTC, Springstone requested changes
@aarunraaj Looks good, almost there. However, we also need to update the portal accelerator (remove Audit option) and eslzArm (remove parameters toplevelmanagementgroupprefix and policyEffect).

2023-03-30 15:53 UTC, aarunraaj commented
> @aarunraaj Looks good, almost there. However, we also need to update the portal accelerator (remove Audit option) and eslzArm (remove parameters toplevelmanagementgroupprefix and policyEffect).

@Springstone, this is complete, and ran another successful test.

2023-04-03 08:34 UTC, Springstone commented
@aarunraaj many thanks, can you kindly merge branch conflicts on this pull request.

2023-04-03 08:37 UTC, Springstone approved these changes
Looks good.

2023-04-05 09:13 UTC, jtracey93 approved these changes

2023-04-05 09:13 UTC, merged