Added support for resource-specific destination table for Firewall
Azure/Enterprise-Scale pull request #1334
Opened 2023-05-28 16:52 UTC by picccard

## Overview/Summary

This allows consumers to use the resource-specific destination table in diag settings for AzFirewalls. Ref. issue #1283

## This PR fixes/adds/changes/removes

1. Adds support for setting resource-specific destination table in diagnostic setting for Azure Firewall

### Breaking Changes

None, optional parameter. Default value is the same as todays default value.

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

### Testing URLs

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fpicccard%2FEnterprise-Scale%2Fdiagsettings-afw-destinationtype%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fpicccard%2FEnterprise-Scale%2Fdiagsettings-afw-destinationtype%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fpicccard%2FEnterprise-Scale%2Fpicccard%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fpicccard%2FEnterprise-Scale%2Fdiagsettings-afw-destinationtype%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2023-05-29 13:55 UTC, Springstone approved these changes
LGTM

2023-05-30 11:51 UTC, jtracey93 commented
@picccard & @Springstone seems there is an issue with the template here, can you investigate https://github.com/Azure/Enterprise-Scale/actions/runs/5120770157/jobs/9207677548?pr=1334

2023-05-30 12:42 UTC, Springstone commented on src/resources/Microsoft.Authorization/policyDefinitions/Deploy-Diagnostics-Firewall.json
> +                      "logAnalyticsDestinationType": "[[parameters('logAnalyticsDestinationType')]"
This is the issue, there is a "," missing at the end of the line.

2023-05-30 12:42 UTC, Springstone requested changes
Found the issue.

2023-05-30 14:00 UTC, jtracey93 approved these changes

2023-05-30 14:00 UTC, merged