PR for User Stories 28609 and 28620
Azure/Enterprise-Scale pull request #1339
Opened 2023-05-30 16:03 UTC by pkorolo

## Overview/Summary

PR for User Stories 28609 and 28620

## This PR fixes/adds/changes/removes

1. adds custom policy for 'Storage Accounts with SFTP enabled should be denied'
2. adds custom policy for 'Subnets without Private Endpoint Network Policies enabled should be denied'

### Breaking Changes

1. None known

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [x] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2023-05-31 10:50 UTC, pkorolo commented
Tests & evidence:

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/b0adb243-6b0c-4e53-bb91-8347aaec5f58)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/d4aa18da-2c45-462f-aa90-aaf3be318145)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/21242a6d-1200-4ac2-9ac8-46f1bb4301cd)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/754c3d2d-73cf-4391-8714-a1fb28c04afe)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/7332a607-1bab-43b5-bef5-fcabda7088a8)

2023-06-02 06:05 UTC, pkorolo commented
converting this to draft again, to add user story 28607

2023-06-02 15:37 UTC, pkorolo commented
Test and evidence for the third custom policy addition:

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/40185585-0a38-481f-ad19-26cd1fc2d4c1)


![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/661c14b8-716c-447d-891c-b204d1dcbd36)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/4196fb28-dee7-4b12-95ba-aac0df025cf4)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/818ba648-ea33-4ad3-9d75-286310c5213d)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/9174204a-04cf-4818-a65c-0e4d0cc25ff4)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/36c69e69-69ab-4eea-9543-b45b6ba40d9f)

![image](https://github.com/Azure/Enterprise-Scale/assets/60117125/d1e17dee-1508-4af3-9983-f9fe61b411a6)

2023-06-02 15:38 UTC, pkorolo commented
All code for the three (3) User Stories included, please review.

2023-06-13 10:59 UTC, Springstone commented on docs/wiki/Whats-new.md
> +- Added new custom policies for:
Could you please move all the new policies under June so they are grouped together.

2023-06-13 11:01 UTC, Springstone requested changes
Hi @pkorolo, one small change for the What's New section, and can you please resolve the merge conflict.

2023-06-13 16:52 UTC, Springstone approved these changes

2023-06-13 17:33 UTC, merged