Denyactionpr
Azure/Enterprise-Scale pull request #1406
Opened 2023-08-17 13:03 UTC by JamJarchitect

## Overview/Summary

Implementation of DenyAction Delete into Azure Landing Zones for both Activity Logs and Diagnostic Settings as two seperate policy definitions and a policy initiative. 

Address story [AB#29619](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/29619)

## This PR fixes/adds/changes/removes

1. Two policy definitions for DenyAction Delete Activity Logs and Diagnostic Settings
2. A policy initiative to apply these two policy definitions

### Breaking Changes

1. N/A

## Testing Evidence

To Be Delivered.

### Testing URLs

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fus29619%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fus29619%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fus29619%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FJamJarchitect%2FEnterprise-Scale%2Fus29619%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [] Performed testing and provided evidence.
- [X] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [X] Updated relevant and associated documentation.
- [X] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2023-08-17 13:38 UTC, Springstone requested changes
Minor What's New updates

2023-08-17 13:38 UTC, Springstone commented on docs/wiki/Whats-new.md
> +  - Additional policy definitions:
```suggestion
  - Adding `DenyAction` policy definitions:
```

2023-08-17 13:38 UTC, Springstone commented on docs/wiki/Whats-new.md
> +    - These two policy definitions prevent Activity Log Settings and Diagnostic Settings being deleted leveraging Azure Policy DenyAction functionality
```suggestion
    - These two policy definitions prevent Activity Log Settings and Diagnostic Settings being deleted leveraging Azure Policy DenyAction functionality
    - Additionally including an initiative that includes both `DenyAction` policies
```

2023-08-25 15:04 UTC, jtracey93 commented
@JamJarchitect & @Springstone are we also looking to add tests for this one?

2023-09-04 13:09 UTC, jtracey93 commented
@Springstone @JamJarchitect - whats the latest with this one?

2023-09-18 09:30 UTC, merged