Defender for Cloud provisioning cleanup - remove D4C DNS and VM Vulnerability Assessment Provider
Azure/Enterprise-Scale pull request #1577
Opened 2024-02-16 14:51 UTC by Springstone

## Overview/Summary

Defender for Cloud provisioning cleanup - remove D4C DNS and VM Vulnerability Assessment Provider

Defender for Cloud for DNS is deprecated and replaced by features in Defender for Servers.
The vulnerability assessment provider for Qualys is being deprecated, and the default ("mdeTvm") - Microsoft Defender for Endpoint Thread Vulnerability Management is the only option going forward.

Note: This change requires deleting the existing assignment and initiative before re-applying.

## This PR fixes/adds/changes/removes

1. Updates to initiatives and assignments

### Breaking Changes

1. Breaking for initiative: Deploy-MDFC-Config
2. Breaking for assignment: DINE-MDFCConfigPolicyAssignment

## As part of this Pull Request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [X] Performed testing and provided evidence.
- [X] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [X] Updated relevant and associated documentation.
- [X] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2024-03-19 13:12 UTC, jtracey93 requested changes

2024-03-19 13:12 UTC, jtracey93 commented on src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json
shouldnt we be following https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide#breaking-changes

2024-03-20 18:07 UTC, jtracey93 submitted a review, later dismissed
just one change @Springstone

2024-03-20 18:07 UTC, jtracey93 commented on src/templates/policies.bicep
> -    loadTextContent('../resources/Microsoft.Authorization/policySetDefinitions/Deploy-MDFC-Config.json') // See AzureChinaCloud and AzureUSGovernment comments below for reasoning
we still need to leave the old one there as this will break Bicep & TF automation. So just duplicate this line to add the new initiative 

Cheers

2024-04-22 11:58 UTC, Springstone commented
@jtracey93 Can I merge this? It's been pending for a while.

2024-05-03 16:31 UTC, jtracey93 approved these changes

2024-05-07 08:34 UTC, merged