Private DNS Zones- Bug Fix1485
Azure/Enterprise-Scale pull request #1578
Opened 2024-02-21 10:24 UTC by rozkurt

## Overview/Summary

This PR is targeting bug report https://github.com/Azure/Enterprise-Scale/issues/1485 and it's adding new built-in policies into "Deploy-Private-DNS-Zones" initiative and assignment. All the new policy names are documented on `Whats-New` file.

## This PR fixes/adds/changes/removes

1. Updated `Deploy-Private-DNS-Zones.json`
2. Updated `DINE-PrivateDNSZonesPolicyAssignment.json`
3. Updated `eslz-portal.json`

### Breaking Changes

1. N\A

## Testing Evidence

![Ekran görüntüsü 2024-02-21 114252](https://github.com/Azure/Enterprise-Scale/assets/72864397/ceb918ce-eff5-4875-9e36-51904aa9caf9)
![Ekran görüntüsü 2024-02-21 115305](https://github.com/Azure/Enterprise-Scale/assets/72864397/f5c5b31b-6ea7-4342-890c-0a5b5d7983d1)
![Ekran görüntüsü 2024-02-21 115446](https://github.com/Azure/Enterprise-Scale/assets/72864397/62b3ad0e-4459-4d22-be0b-0e8c8bbe293b)

### Testing URLs

#### Azure Public

[![Deploy To Azure](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Frozkurt%2FEnterprise-Scale-rozkurt%2FPrivateDNSZones_BugFix1485%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Frozkurt%2FEnterprise-Scale-rozkurt%2FPrivateDNSZones_BugFix1485%2FeslzArm%2Feslz-portal.json)

## As part of this Pull Request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [x] Performed testing and provided evidence.
- [x] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [x] Updated relevant and associated documentation.
- [x] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2024-03-05 14:48 UTC, jtracey93 requested changes
just a couple of changes please @rozkurt 

cc: @Springstone

2024-03-05 14:48 UTC, jtracey93 commented on docs/wiki/Whats-new.md
> +  - [AMA Update for the Portal Accelerator](#AMA-Update-for-the-Portal-Accelerator)
duplicated from lines 4 & 5?

2024-03-05 16:07 UTC, rozkurt commented on docs/wiki/Whats-new.md
> +  - [AMA Update for the Portal Accelerator](#AMA-Update-for-the-Portal-Accelerator)
@jtracey93 I just removed duplicated lines!

2024-03-07 10:13 UTC, Springstone approved these changes
LGTM

2024-03-08 10:06 UTC, jtracey93 approved these changes

2024-03-08 10:06 UTC, merged