AddExclusionListToPolicy
Azure/Enterprise-Scale pull request #1731
Opened 2024-08-16 14:40 UTC by BeckyHope19

## Overview/Summary

The pull request being submitted is for a policy update to Deny vNet peering to other subscriptions, this update includes a new parameter to allow for vnets in other subscriptions.

## This PR fixes/adds/changes/removes

1. This change adds a parameter field to exclude certain vNets from being denied to peer with vNets in different subscriptions.

### Breaking Changes

1. N/A

## Testing Evidence

 I carried out tests in my test subscription with 4 vnets, 2 were in the same subscription and the other 2 were in another subscription. vNet 1 & 3 sit in Subscription 1 and vNet 2 & 4 sit in Subscription 2. Both subscription sit under the bex19 management group scope. 

Here you will see the policy has been assigned to the bex19 management group scope, this is where the vnets also sit.
![PolicyAssigned](https://github.com/user-attachments/assets/79a1341a-7b65-4d03-b8f2-fd4af65fd71d)

You can then see the parameters I have passed in the policy for vNet 1 & 2 to be allowed to peer, you can see the subscription ID is different in the screenshot:
![PolicyParameters](https://github.com/user-attachments/assets/7e049bd9-9dfb-4178-b5c0-b6b450dd8699)

Here I am trying to create a peering between vNet 3 & 4, you will see it fails as neither of the vNets are in the allowed list and they are both in different subscriptions:
![vnet 3-4 failed peering](https://github.com/user-attachments/assets/84da7e2e-dc8d-495d-bea2-c3ad8b1142f2)

Here I have created a peering between vNet 1 & 3, you will see it is successful as they are both in the same subscription:
![vnet 1-3 successful peering](https://github.com/user-attachments/assets/9bf0b619-7b40-49f4-a2b0-86814b19817a)

Here I have created a peering between vNet 2 & 4, you will see it is successful as they are both in the same subscription:
![vnet 2-4 successful peering](https://github.com/user-attachments/assets/93d1d8c2-7868-4823-9ea6-760198d45393)

Here I have created a peering between vNet 1 & 2, you will see it is successful as they are both in the allowed list:
![vnet 1-2 successful peering](https://github.com/user-attachments/assets/78dc56df-c44e-4a49-bc92-afe60acc72e0)

Here I am trying to create a peering between vNet 1 & 4, you will see it fails because only vNet 1 is in the allowed list and vNet 4 isn't, so it is only allowing the peering one way:
![vnet 1-4 failed peering](https://github.com/user-attachments/assets/5b2b1c21-f5a5-4368-9208-1481819a233b)

The below URLs can be updated where the placeholders are, look for `BeckysBranchALZ-07-08-24` & `BeckysBranchALZ-07-08-24`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#view/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2FBeckyHope19%2FEnterprise-Scale%2FBeckysBranchALZ-07-08-24%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2FBeckyHope19%2FEnterprise-Scale%2FBeckysBranchALZ-07-08-24%2FeslzArm%2Feslz-portal.json)

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2024-08-16 15:05 UTC, BeckyHope19 commented
@Springstone please fix this for me :-)

2024-08-19 11:05 UTC, Springstone requested changes
Great contribution. Couple of small things, and please can you also update "Whatsnew.md" in the wiki under the Policy Refresh section to include a short description on what you changed. 
Once you've changed the policy version, please re-run the policy build script.

2024-08-19 11:05 UTC, Springstone commented on src/resources/Microsoft.Authorization/policyDefinitions/Deny-VNET-Peer-Cross-Sub.json
> +      "version": "1.0.2",
As we are adding a new parameter, we need to increment the minor version of the policy as per https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Policies#versioning.
Please change policy version to "1.1.0".

2024-08-19 14:39 UTC, BeckyHope19 commented
@Springstone - I have added the changes to the parameters as requested and updated the Whats New page and run the build command again.

2024-08-21 08:02 UTC, Springstone approved these changes

2024-08-27 12:07 UTC, jtracey93 approved these changes

2024-08-27 12:08 UTC, merged