Include all fix to a workable version for mooncake (Azure China)
Azure/Enterprise-Scale pull request #1759
Opened 2024-09-06 09:19 UTC by yuanzhang9

Changes on initiative definition and assignment due to missing build-in policy in mooncake:
Add new policy assignments à eslzArm\managementGroupTemplates\policyAssignments\china
Add new initiatives definition à src\resources\Microsoft.Authorization\policySetDefinitions
Update Bicep file on context loading à src\templates\initiatives.bicep, src\templates\policies.bicep
Update ARM template to load different assignments à eslzArm\eslzArm.json
 

Changes on role assignment due to service
Disable role “Security Operation” and “Network Management” as service “Microsoft.Support/*” is not available in mooncake. à src\templates\roles.bicep

Hide some option from Portal GUI as the service/policy/initiative are not available nor supported in mooncake. à eslzArm\eslz-portal.json
 

Change on service configuration:
Add new configuration file for Azure Defender for Cloud since the 2024-01-01version of API(Microsoft.Security/pricings) is not supported. à  eslzArm\subscriptionTemplates\mcmdfcConfiguration.json

2024-09-26 12:27 UTC, Springstone requested changes
Couple of things to review, and please address the conflicts

2024-09-30 02:45 UTC, yuanzhang9 commented on src/resources/Microsoft.Authorization/policySetDefinitions/Enforce-ALZ-Decomm.json
> +          "AzureChinaCloud"
Yes, nice spot. It should be "AzureUSGovernment"  instead.

2024-09-30 06:20 UTC, yuanzhang9 commented on src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.AzureChinaCloud.json
> +      "version": "1.2.0",
I've adjusted it to 1.1.0 and completed the test. Thanks~

2024-09-30 09:42 UTC, yuanzhang9 commented
One more update for "Routing intent of vWAN hub", included in this PR as well.

2024-10-29 04:04 UTC, Springstone approved these changes

2024-10-29 04:04 UTC, merged