feat: allow single parameter dns zone policy
Azure/Enterprise-Scale pull request #1821
Opened 2024-11-01 18:14 UTC by jaredfholgate

## Overview/Summary

A backwards compatible update to the Deploy-Private-DNS-Zones policy set definition.

This enables passing a subscription id, resource group name and region to automatically generate the resource ids for the policy definitions.

## This PR fixes/adds/changes/removes

N/A

### Breaking Changes

None, designed to be backwards compatible

## Testing Evidence

Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).

### Testing URLs

The below URLs can be updated where the placeholders are, look for `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}` & `{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}`, to allow you to test your portal deployment experience.

> Please also replace the curly brackets on the placeholders `{}`

#### Azure Public

[![Deploy To Azure](https://learn.microsoft.com/en-us/azure/templates/media/deploy-to-azure.svg)](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2Feslz-portal.json)

#### Azure US Gov (Fairfax)
[![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazuregov.svg?sanitize=true)](https://portal.azure.us/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2F{YOUR GITHUB ORG/ACCOUNT HERE - Remove Curly Brackets Also}%2FEnterprise-Scale%2F{YOUR GITHUB BRANCH NAME HERE - Remove Curly Brackets Also}%2FeslzArm%2Ffairfaxeslz-portal.json)

## As part of this Pull Request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [ ] Performed testing and provided evidence.
- [ ] Ensured [contribution guidance](https://github.com/Azure/Enterprise-Scale/wiki/ALZ-Contribution-Guide) is followed.
- [ ] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2024-11-01 18:29 UTC, matt-FFFFFF commented on src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
> +          "uaenorth" : "uan",
nit - is it worth sorting these for ease of maintenance?

2024-11-01 18:29 UTC, matt-FFFFFF commented on src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
> +          "azureFilePrivateDnsZoneId": "privatelink.afs.azure.net",
again is it worth sorting these?

2024-11-01 18:29 UTC, matt-FFFFFF commented on src/resources/Microsoft.Authorization/policySetDefinitions/Deploy-Private-DNS-Zones.json
> +          "displayName": "azureSiteRecoveryBackupPrivateDnsZoneId",
👏 👏 👏 

Love this

2024-11-04 16:05 UTC, matt-FFFFFF commented
I get this error when trying to deploy the policy set. Investigating...


`Bad Request({"error":{"code":"InvalidPolicyParameters","message":"A function or parameter in policy set or assignment 'Deploy-Private-DNS-Zones' associated with the policy definition '06695360-db88-47f6-b976-7500d4297475' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The language expression property '' doesn't exist, available properties are 'uaenorth, northcentralus, malaysiawest, eastus, uksouth, westcentralus, israelcentral, southeastasia, malaysiasouth, koreacentral, northeurope, australiaeast, southafricanorth, norwaywest, norwayeast, westus3, eastus2euap, centralus, mexicocentral, canadacentral, japaneast, swedencentral, taiwannorth, germanynorth, centralindia, westindia, newzealandnorth, australiacentral, ukwest, germanywestcentral, brazilsouth, francecentral, brazilsoutheast, westus2, eastus2, centraluseuap, australiacentral2, francesouth, southafricawest, koreasouth, southindia, canadaeast, qatarcentral, spaincentral, westeurope, japanwest, southcentralus, polandcentral, switzerlandwest, australiasoutheast, switzerlandnorth, italynorth, uaecentral, eastasia, chilecentral, westus, swedensouth'.'."}})`

2024-11-04 18:14 UTC, jaredfholgate commented
> I get this error when trying to deploy the policy set. Investigating...
> 
> `Bad Request({"error":{"code":"InvalidPolicyParameters","message":"A function or parameter in policy set or assignment 'Deploy-Private-DNS-Zones' associated with the policy definition '06695360-db88-47f6-b976-7500d4297475' could not be validated. If using template functions, try following the tips in: https://aka.ms/policy-avoiding-template-failures. The inner exception 'The language expression property '' doesn't exist, available properties are 'uaenorth, northcentralus, malaysiawest, eastus, uksouth, westcentralus, israelcentral, southeastasia, malaysiasouth, koreacentral, northeurope, australiaeast, southafricanorth, norwaywest, norwayeast, westus3, eastus2euap, centralus, mexicocentral, canadacentral, japaneast, swedencentral, taiwannorth, germanynorth, centralindia, westindia, newzealandnorth, australiacentral, ukwest, germanywestcentral, brazilsouth, francecentral, brazilsoutheast, westus2, eastus2, centraluseuap, australiacentral2, francesouth, southafricawest, koreasouth, southindia, canadaeast, qatarcentral, spaincentral, westeurope, japanwest, southcentralus, polandcentral, switzerlandwest, australiasoutheast, switzerlandnorth, italynorth, uaecentral, eastasia, chilecentral, westus, swedensouth'.'."}})`

Thanks for testing it. I will take a look and try to fix it. :)

2024-11-04 23:36 UTC, matt-FFFFFF approved these changes, later dismissed

2024-11-05 06:27 UTC, Springstone requested changes, later dismissed
Busy testing deployment. Please add a meaningful update to What's New wiki.

2024-11-05 09:05 UTC, jtracey93 requested changes

2024-11-05 09:05 UTC, jtracey93 commented on utils/policyTesting/Install-PolicySetDefinitions.ps1
Whats this for? I can see it deploy the policy set defs to an MG, but just wondering where its used?

2024-11-05 09:13 UTC, jaredfholgate commented on utils/policyTesting/Install-PolicySetDefinitions.ps1
As mentioned, it is for local testing purposes. Can add equivalent for policy definitions and policy assignments too eventually.

2024-11-05 11:25 UTC, jtracey93 requested changes

2024-11-05 11:25 UTC, jtracey93 commented on utils/policyTesting/Install-PolicySetDefinitions.ps1
> +  $managementGroupId = "6da17bdb-c2cc-4a35-8f10-cded38ebfc47",
```suggestion
  $managementGroupId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
```

2024-11-05 11:28 UTC, jtracey93 approved these changes

2024-11-05 12:40 UTC, merged