Add Trey Research
Azure/Enterprise-Scale pull request #442
Opened 2021-02-26 16:25 UTC by rjfmachado

This adds the main Readme links to Trey Research.

2021-02-27 10:22 UTC, krnese requested changes

2021-03-01 09:36 UTC, rjfmachado commented on README.md
> +| Trey Research | For small and medium Enterprises | [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?saniti
The readme contains:
This reference implementation provides a design path and initial technical state for Small and Medium Enterprises to start with foundational landing zones that support their application portfolios.

2021-03-01 09:41 UTC, rjfmachado commented on README.md
> +| Trey Research | For small and medium Enterprises | [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?saniti
we could also use "for small IT teams" ?

2021-03-01 09:43 UTC, krnese commented on README.md
> +| Trey Research | For small and medium Enterprises | [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?saniti
Can you pls correct so it calls out small enterprise as agreed? 
![image](https://user-images.githubusercontent.com/12991708/109479702-f3cf9b00-7a7a-11eb-8cfc-6dd53bc0247f.png)

2021-03-01 12:35 UTC, rjfmachado commented on README.md
> +| Trey Research | For small and medium Enterprises | [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?saniti
Should be good now @krnese

2021-03-01 13:39 UTC, krnese approved these changes

2021-03-01 13:40 UTC, merged