Added new Trey Research reference implementation
Azure/Enterprise-Scale pull request #488
Opened 2021-04-09 07:55 UTC by victorp13

Added new Trey Research reference implementation. It _is_ listed on the README.md, but not here.

**This PR fixes**
a missing reference to the new Trey Research reference implementation.

2021-04-09 12:02 UTC, krnese approved these changes

2021-04-21 09:16 UTC, hjscherer requested changes

2021-04-21 09:16 UTC, hjscherer commented on docs/EnterpriseScale-Deploy-reference-implentations.md
> +| Trey Research | For small Enterprises | [![Deploy To Azure](https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/1-CONTRIBUTION-GUIDE/images/deploytoazure.svg?sanitize=true)](h
Please update the link to "Detailed description". Link is broken -> 404

2021-05-07 08:38 UTC, hjscherer commented
@victorp13 I'm closing this PR now. Update made it already into the MD file. Let us know if you want to update anything else.

2021-05-07 08:38 UTC, closed without merging