Vwan availability zones
Azure/Enterprise-Scale pull request #960
Opened 2022-04-18 20:50 UTC by jhajduk-microsoft

## Overview/Summary

Adding availability zones to the Azure Firewall that is part of the managed VWAN hub template
## This PR fixes/adds/changes/removes

1. Implementing functionality consistent with supported features of Azure Firewall used with Azure Managed virtual wan

### Breaking Changes

None

## Testing Evidence

[Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate).](https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjhajduk-microsoft%2FEnterprise-Scale%2Fvwan-availability-zones%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjhajduk-microsoft%2FEnterprise-Scale%2Fvwan-availability-zones%2FeslzArm%2Feslz-portal.json)

## As part of this Pull Request I have

- [Y] Checked for duplicate [Pull Requests](https://github.com/Azure/Enterprise-Scale/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/Enterprise-Scale/issues), for tracking and closure.
- [Y] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Enterprise-Scale/tree/main)
- [Y] Performed testing and provided evidence.
- [Y] Updated relevant and associated documentation.
- [ ] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located: `/docs/wiki/whats-new.md`)

2022-04-18 20:51 UTC, jhajduk-microsoft commented
@jtracey93 - Let me know if other changes are needed as part of this

2022-05-05 22:55 UTC, jhajduk-microsoft commented
@jtracey93 - I believe I have added in the correct places now, but when I go to the firewall and look at properties, the availability zones property is empty: https://portal.azure.com/#blade/Microsoft_Azure_CreateUIDef/CustomDeploymentBlade/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fjhajduk-microsoft%2FEnterprise-Scale%2Fvwan-availability-zones%2FeslzArm%2FeslzArm.json/uiFormDefinitionUri/https%3A%2F%2Fraw.githubusercontent.com%2Fjhajduk-microsoft%2FEnterprise-Scale%2Fvwan-availability-zones%2FeslzArm%2Feslz-portal.json

2022-05-08 07:51 UTC, jtracey93 requested changes
A few small additions

2022-05-08 07:51 UTC, jtracey93 commented on docs/wiki/Whats-new.md
> +
```suggestion

- *No updates, yet.*

```

2022-05-08 07:51 UTC, jtracey93 commented on docs/wiki/Whats-new.md
> +
```suggestion

- *No updates, yet.*

```

2022-05-08 08:02 UTC, jtracey93 commented on eslzArm/eslz-portal.json
> +                            "visible": "[if(equals(steps('esConnectivityGoalState').esHub, 'vhub'), or(equals(steps('esConnectivityGoalState').esHub, 'vwan'), and(equals(steps('esConnectivityGoalStat
```suggestion
                            "visible": "[if(equals(steps('esConnectivityGoalState').esHub, 'vhub'), or(equals(steps('esConnectivityGoalState').esHub, 'vwan')), and(equals(steps('esConnectivityGoalState').esAzFw,'Yes'), contains(split('canadacentral,centralus,eastus,eastus2,southcentralus,westus2,francecentral,germanywestcentral,northeurope,westeurope,uksouth,southafricanorth,japaneast,southeastasia,australiaeast', ','), steps('esConnectivityGoalState').esNwLocation)), false)]",
```

2022-05-08 08:03 UTC, jtracey93 commented on eslzArm/fairfaxeslz-portal.json
> +                            "visible": "[if(equals(steps('esConnectivityGoalState').esHub, 'vhub'), or(equals(steps('esConnectivityGoalState').esHub, 'vwan'), and(equals(steps('esConnectivityGoalStat
```suggestion
                            "visible": "[if(equals(steps('esConnectivityGoalState').esHub, 'vhub'), or(equals(steps('esConnectivityGoalState').esHub, 'vwan')), and(equals(steps('esConnectivityGoalState').esAzFw,'Yes'), contains(split('canadacentral,centralus,eastus,eastus2,southcentralus,westus2,francecentral,germanywestcentral,northeurope,westeurope,uksouth,southafricanorth,japaneast,southeastasia,australiaeast', ','), steps('esConnectivityGoalState').esNwLocation)), false)]",
```

2022-05-09 16:12 UTC, jtracey93 commented
Testing Evidence:
![image](https://user-images.githubusercontent.com/41163455/167452195-7550854d-2b3d-48dd-bb89-17a4442ef59e.png)
![image](https://user-images.githubusercontent.com/41163455/167452269-873cdf43-04bb-4166-b276-992802931fd6.png)
![image](https://user-images.githubusercontent.com/41163455/167452286-09fe755d-7cd9-4806-90ab-0d8fceb416d7.png)
![image](https://user-images.githubusercontent.com/41163455/167452299-73dc26cd-fb92-4faa-b8ab-dcde8b76b4de.png)

2022-05-09 16:18 UTC, merged